-- ============================================================================
-- V1__create_domain_tables.sql
-- Clyvo VET — Criacao das tabelas de dominio do ecossistema
-- ============================================================================

CREATE TABLE t_clyvo_clinica (
    id_clinica   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_clinica   VARCHAR(100) NOT NULL,
    nr_cnpj      VARCHAR(18)  NOT NULL UNIQUE,
    ds_endereco  VARCHAR(200) NOT NULL,
    nr_telefone  VARCHAR(15)  NOT NULL,
    ds_email     VARCHAR(100)
);

CREATE TABLE t_clyvo_veterinario (
    id_veterinario   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_veterinario   VARCHAR(100) NOT NULL,
    nr_crmv          VARCHAR(20)  NOT NULL UNIQUE,
    ds_especialidade VARCHAR(80),
    nr_telefone      VARCHAR(15),
    id_clinica       BIGINT       NOT NULL,
    CONSTRAINT fk_clyvo_vet_clinica FOREIGN KEY (id_clinica) REFERENCES t_clyvo_clinica (id_clinica)
);

CREATE TABLE t_clyvo_tutor (
    id_tutor     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tutor     VARCHAR(100) NOT NULL,
    nr_cpf       VARCHAR(14)  NOT NULL UNIQUE,
    ds_email     VARCHAR(100) NOT NULL,
    nr_telefone  VARCHAR(15)  NOT NULL,
    ds_endereco  VARCHAR(200)
);

CREATE TABLE t_clyvo_pet (
    id_pet        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_pet        VARCHAR(60) NOT NULL,
    ds_especie    VARCHAR(30) NOT NULL,
    ds_raca       VARCHAR(50),
    dt_nascimento DATE,
    nr_peso       DOUBLE PRECISION,
    id_tutor      BIGINT      NOT NULL,
    CONSTRAINT fk_clyvo_pet_tutor FOREIGN KEY (id_tutor) REFERENCES t_clyvo_tutor (id_tutor)
);

CREATE TABLE t_clyvo_agendamento (
    id_agendamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_agendamento TIMESTAMP    NOT NULL,
    ds_tipo        VARCHAR(30)  NOT NULL,
    ds_status      VARCHAR(20)  NOT NULL,
    ds_observacao  VARCHAR(300),
    id_pet         BIGINT       NOT NULL,
    id_veterinario BIGINT       NOT NULL,
    CONSTRAINT fk_clyvo_agend_pet FOREIGN KEY (id_pet) REFERENCES t_clyvo_pet (id_pet),
    CONSTRAINT fk_clyvo_agend_vet FOREIGN KEY (id_veterinario) REFERENCES t_clyvo_veterinario (id_veterinario)
);

CREATE TABLE t_clyvo_evento_saude (
    id_evento       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_tipo_evento  VARCHAR(30)  NOT NULL,
    dt_evento       DATE         NOT NULL,
    ds_descricao    VARCHAR(500) NOT NULL,
    ds_resultado    VARCHAR(300),
    id_pet          BIGINT       NOT NULL,
    id_veterinario  BIGINT       NOT NULL,
    CONSTRAINT fk_clyvo_evento_pet FOREIGN KEY (id_pet) REFERENCES t_clyvo_pet (id_pet),
    CONSTRAINT fk_clyvo_evento_vet FOREIGN KEY (id_veterinario) REFERENCES t_clyvo_veterinario (id_veterinario)
);

CREATE TABLE t_clyvo_protocolo (
    id_protocolo      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_especie        VARCHAR(30)  NOT NULL,
    ds_raca           VARCHAR(50),
    ds_tipo_protocolo VARCHAR(30)  NOT NULL,
    ds_descricao      VARCHAR(500) NOT NULL,
    nr_intervalo_dias INTEGER      NOT NULL,
    ds_faixa_etaria   VARCHAR(30)
);
