-- ============================================================================
-- V2__create_security_tables.sql
-- Clyvo VET — Criacao da tabela de usuarios e controle de perfis (Spring Security)
-- ============================================================================

CREATE TABLE t_clyvo_usuario (
    id_usuario     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario     VARCHAR(100) NOT NULL,
    ds_email       VARCHAR(100) NOT NULL UNIQUE,
    ds_senha       VARCHAR(255) NOT NULL,
    ds_role        VARCHAR(30)  NOT NULL,
    st_ativo       BOOLEAN      DEFAULT TRUE NOT NULL,
    id_tutor       BIGINT,
    id_veterinario BIGINT
);

CREATE INDEX idx_clyvo_usuario_email ON t_clyvo_usuario(ds_email);
